### ISSUE TITLE
Super Crate Box Game Boy Advance implementation by Peter Black

### ISSUE THREAD

**Issue by jan-kleks** [exelotl/nim-tonc#1]
Since you are working on your own implementation, I thought that maybe you will find something useful for your project: https://github.com/Peter-black/SuperCrateBox-GBA

Regards

**Comment by exelotl** [comment]
Hey, thanks for the link! I wasn't aware of this port. I think my SCB project is quite a bit more advanced than this already, but it's always good to know about related projects, and it's super cool that they made the source available.

You might find this interesting: I was chatting to someone a couple years ago who made a very nice splash/title demo. I don't think he developed it further but hey it looks and sounds great and has a clever name, maybe I'll ask him I can use that name some time x) https://www.youtube.com/watch?v=sv2Y8Ly6MCE

**Comment by jan-kleks** [comment]
Sorry for bothering you again, you are probably busy with your other projects... But have you seen this cool "flying" variant of Super Crate Box for PICO-8? -- https://farbs.itch.io/super-disc-box Together with the original game, it would make a really awesome 2-in-1 GBA cartridge...

**Comment by exelotl** [comment]
Oh my god that's fantastic! I love the 2-in-1 idea, thanks for sharing. :)

I'm sorry for not delivering on my own SCB port, there's just so many things to work on these days. But I haven't forgotten about it, and I do still want to finish it.
